CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "PredictionFeedback" (
    "PredictionFeedbackId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp with time zone NULL,
    "WasCorrect" boolean NOT NULL,
    "Description" text NOT NULL,
    "ImageChecksum" text NOT NULL,
    "Prediction" text NOT NULL,
    CONSTRAINT "PK_PredictionFeedback" PRIMARY KEY ("PredictionFeedbackId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220816154330_InitialCreate', '6.0.8');

COMMIT;

