// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;

namespace BirdIdentifier.MlModel;

public class BirdClassificationModelV1
{
    public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
    {
        var pipeline = BuildPipeline(context);
        var model = pipeline.Fit(trainData);

        return model;
    }

    /// <summary>
    ///     build the pipeline that is used from model builder. Use this function to retrain model.
    /// </summary>
    /// <param name="mlContext"></param>
    /// <returns></returns>
    public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
    {
        // Data process configuration with pipeline data transformations
        var pipeline = mlContext.Transforms.Conversion.MapValueToKey(@"Label", @"Label")
            .Append(mlContext.Transforms.LoadRawImageBytes(@"ImageSource_featurized", @"", @"ImageSource"))
            .Append(mlContext.Transforms.CopyColumns(@"Features", @"ImageSource_featurized"))
            .Append(mlContext.MulticlassClassification.Trainers.ImageClassification())
            .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

        return pipeline;
    }
}